apiVersion: apps/v1
kind: Deployment
metadata:
  name: truyumwebapi
  labels:
    app: truyumwebapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: truyumwebapi  
  template:
    metadata:
      labels:
        app: truyumwebapi
    spec:
      containers:
      - name: truyumwebapi
        image: truyumregistry.azurecr.io/new:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: truyumconsvcsecret
---
apiVersion: v1
kind: Service
metadata:
  name: truyumwebapisvc
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: truyumwebapi